from typing import Literal

from pydantic import BaseModel, Field


class ProjectConfig(BaseModel):
    """Input configuration for a generated short-form video."""

    topic: str = Field(min_length=3)
    language: str = "es"
    duration_seconds: int = Field(default=45, ge=10, le=180)
    aspect_ratio: Literal["9:16"] = "9:16"
    audience: str = "general"
    style: str = "cinematic documentary"


class Script(BaseModel):
    """Narrative result generated by the script-writing agent."""

    title: str
    hook: str
    narration: str


class Scene(BaseModel):
    """Atomic audiovisual unit used by the rest of the pipeline."""

    id: int = Field(ge=1)
    narration: str
    visual_prompt: str
    negative_prompt: str | None = None
    camera_motion: str = "slow push in"
    transition: str = "cut"
    duration_hint_seconds: float | None = Field(default=None, gt=0)


class VideoPlan(BaseModel):
    """Central contract passed between generation stages."""

    project: ProjectConfig
    title: str
    visual_style: str
    scenes: list[Scene] = Field(min_length=1)
