from typing import Literal

from pydantic import BaseModel, Field


class ProjectConfig(BaseModel):
    """Project-level configuration shared across production stages."""

    topic: str = Field(min_length=3)
    language: str = "es"
    duration_seconds: int = Field(default=45, ge=10, le=180)
    aspect_ratio: Literal["9:16"] = "9:16"
    audience: str = "general"
    style: str = "cinematic documentary"


class Script(BaseModel):
    """Script generated by the optional Phase 1 script-writing utility."""

    title: str
    hook: str
    narration: str


class SourceScript(BaseModel):
    """Canonical input for the production pipeline."""

    text: str = Field(min_length=1)

    @classmethod
    def from_generated(cls, script: Script) -> "SourceScript":
        """Convert an optional generated script into the production input contract."""

        return cls(text=script.narration)


class NarrativeBlock(BaseModel):
    """A contiguous semantic unit of the source script."""

    id: int = Field(ge=1)
    text: str = Field(min_length=1)


class Beat(BaseModel):
    """A single visualizable action, change, or idea inside a narrative block."""

    id: int = Field(ge=1)
    block_id: int = Field(ge=1)
    action: str = Field(min_length=1)


class Scene(BaseModel):
    """Minimal scene contract: an ordered grouping of narrative beats."""

    id: int = Field(ge=1)
    beat_ids: list[int] = Field(min_length=1)


class StoryboardScene(BaseModel):
    """Legacy rich scene emitted by the experimental Phase 1 DirectorAgent."""

    id: int = Field(ge=1)
    narration: str
    visual_prompt: str
    negative_prompt: str | None = None
    camera_motion: str = "slow push in"
    transition: str = "cut"
    duration_hint_seconds: float | None = Field(default=None, gt=0)


class VideoPlan(BaseModel):
    """Experimental Phase 1 storyboard kept for backwards compatibility."""

    project: ProjectConfig
    title: str
    visual_style: str
    scenes: list[StoryboardScene] = Field(min_length=1)
